services:
  - type: web
    name: carevia
    env: php
    plan: free
    region: oregon
    buildCommand: "./render-build.sh"
    startCommand: "php artisan serve --host=0.0.0.0 --port=$$PORT"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://carevia.onrender.com
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: carevia-db
          property: connectionString
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: sync
      - key: BROADCAST_CONNECTION
        value: log
      - key: FILESYSTEM_DISK
        value: local
      - key: PHP_CLI_SERVER_WORKERS
        value: 4
databases:
  - name: carevia-db
    plan: free
    region: oregon
    databaseName: carevia
    user: carevia
